FormsGeneratorWebApplication/Controllers/FormsAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using FormsGeneratorWebApplication.Models;
using FormsGeneratorWebApplication.Utilities;
using System.Threading.Tasks;
namespace FormsGeneratorWebApplication.Controllers
{
    [Authorize]
    public class FormsAdminController : Controller
    {
        public static int TYPE_TEXT_BOX = 0;
        public static int TYPE_TEXT_AREA = 1;
        public static int TYPE_TEXT_RADIO = 2;
        public static int TYPE_TEXT_CHECKBOX = 3;

        public const int TEMPLATE_FORM_TRUE_OR_FALSE = 2;
        public const int TEMPLATE_FORM_TEXTAREA = 1;
        public const int TEMPLATE_FORM_TEXTBOX = 0;




        //private static FormsDbContext db = new FormsDbContext();
        private static UserStore<ApplicationUser> store = new UserStore<ApplicationUser>(new ApplicationDbContext());
        private static UserManager<ApplicationUser> userManager = new UserManager<ApplicationUser>(store);


        // GET: /FormsAdmin/
        public ActionResult Index()
        {
            FormsDbContext db = new FormsDbContext();
            //Emailer("bluemner@uwm.edu, njjakusz@uwm.edu");
            var curUser = userManager.FindById(User.Identity.GetUserId());
            var formList = new List<FormsModel>();
            var totalList = new List<int>();
            var completedList = new List<int>();
            var index = 0;
            foreach (UserForm uF in curUser.forms)
            {
                Func<FormsModel, bool> compare = delegate(FormsModel form)
                {
                    if (form.adminGUID == uF.formGUID)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                };
                var formToReturn = db.FormModels.First<FormsModel>(compare);
                formList.Add(formToReturn);
                totalList.Add(0);
                completedList.Add(0);
                foreach (ResultModel rM in db.ResultModels)
                {
                    if (rM.adminGUID == formToReturn.adminGUID)
                    {
                        totalList[index]++;
                        if (rM.active == false)
                        {
                            completedList[index]++;
                        }
                    }
                }
                index++;
            }
            var adminFormModel = new AdminFormModel()
            {
                forms = formList,
                total = totalList,
                completed = completedList
            };

            //Analytic("39951b69-b8c1-4a0b-8f19-02223bd6b403");
            //reminder("6099f5d9-b3bf-4846-b8fa-5d3191f64e18");

            return View(adminFormModel);
        }

        [HttpGet]
        public ActionResult MakeForm()
        {

            return View(new FormsModel());

        }

        [HttpPost]
        public ActionResult MakeForm(FormsModel model)
        {
            FormsDbContext db = new FormsDbContext();

            model.adminGUID = createGuid();
            //var x = 3;
            // This logic works, but when the view passes the model to 
            // this function, the model's FormItemList is null
            var curUser = userManager.FindById(User.Identity.GetUserId());
            curUser.forms.Add(new UserForm() { formGUID = model.adminGUID, user = curUser });
            //model.user = user;
            db.FormModels.Add(model);
            Task<IdentityResult> task = userManager.UpdateAsync(curUser);
            //IdentityResult done = await task;
            //store.Context.SaveChanges();
            db.SaveChanges();
            Console.WriteLine("make forms ran");

            ViewBag.GUID = model.adminGUID.ToString();
            return View("Email");
        }

        [HttpGet]
        public ActionResult EditForm(String guid)
        {
            FormsDbContext db = new FormsDbContext();

            var compGUID = Guid.Parse(guid);
            Func<FormsModel, bool> compare = delegate(FormsModel form)
            {
                if (form.adminGUID == compGUID)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            };

            FormsModel result = db.FormModels.First<FormsModel>(compare);

            return View(result);
        }

        [HttpPost]
        public ActionResult EditForm(FormsModel model)
        {
            FormsDbContext db = new FormsDbContext();
            //db.Entry(model).State = System.Data.Entity.EntityState.Modified;
            //foreach (FormItemModel item in model.FormItemIList)
            //{
            //    db.Entry(item).State = System.Data.Entity.EntityState.Modified;
            //}
            Func<FormsModel, bool> keyCompare = delegate(FormsModel form)
            {
                if (form.key == model.key)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            };
            FormsModel result = db.FormModels.First<FormsModel>(keyCompare);
            var deleteQuestionList = new List<FormItemModel>();
            if (result.FormItemIList != null)
            {
                foreach (FormItemModel fIM in result.FormItemIList)
                {
                    deleteQuestionList.Add(fIM);
                    if (fIM.options != null)
                    {
                        var deleteOptionsList = new List<OptionsModel>();
                        foreach (OptionsModel oM in fIM.options)
                        {
                            deleteOptionsList.Add(oM);
                        }
                        foreach (OptionsModel oM in deleteOptionsList)
                        {
                            db.OptionsModels.Remove(oM);
                        }
                    }
                    if (fIM.selected != null)
                    {
                        var deleteSelectedList = new List<SelectedModel>();
                        foreach (SelectedModel oM in fIM.selected)
                        {
                            deleteSelectedList.Add(oM);
                        }
                        foreach (SelectedModel oM in deleteSelectedList)
                        {
                            db.SelectedModels.Remove(oM);
                        }
                    }
                }
                foreach (FormItemModel fIM in deleteQuestionList)
                {
                    db.FormItemModels.Remove(fIM);
                }
            }
            db.FormModels.Remove(result);
            db.SaveChanges();
            db.FormModels.Add(model);
            db.SaveChanges();
            var guid = model.adminGUID;
            var deleteList = new List<ResultModel>();
            foreach (ResultModel rM in db.ResultModels)
            {
                if (rM.adminGUID == guid)
                {
                    deleteList.Add(rM);
                }
            }
            var deleteResultModels = new List<ResultModel>();
            foreach (ResultModel rM in deleteList)
            {
                Func<FormsModel, bool> compare = delegate(FormsModel form)
                {
                    if (form.adminGUID == rM.userGUID)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                };
                var deleteThisForm = db.FormModels.First<FormsModel>(compare);
                if (deleteThisForm.FormItemIList != null)
                {
                    foreach (FormItemModel fIM in deleteThisForm.FormItemIList)
                    {
                        deleteQuestionList.Add(fIM);
                        if (fIM.options != null)
                        {
                            var deleteOptionsList = new List<OptionsModel>();
                            foreach (OptionsModel oM in fIM.options)
                            {
                                deleteOptionsList.Add(oM);
                            }
                            foreach (OptionsModel oM in deleteOptionsList)
                            {
                                db.OptionsModels.Remove(oM);
                            }
                        }
                        if (fIM.selected != null)
                        {
                            var deleteSelectedList = new List<SelectedModel>();
                            foreach (SelectedModel oM in fIM.selected)
                            {
                                deleteSelectedList.Add(oM);
                            }
                            foreach (SelectedModel oM in deleteSelectedList)
                            {
                                db.SelectedModels.Remove(oM);
                            }
                        }
                    }
                    foreach (FormItemModel fIM in deleteQuestionList)
                    {
                        fIM.FormsModel = null;
                        try
                        {
                            db.FormItemModels.Remove(fIM);
                        }
                        catch
                        {

                        }
                    }
                }
                deleteResultModels.Add(rM);
                db.FormModels.Remove(deleteThisForm);
                db.SaveChanges();
            }

FormsGeneratorWebApplication/Views/FormsAdmin/EditForm.cshtml
@using FormsGeneratorWebApplication.Models;

@model FormsModel
@{
    ViewBag.Title = "Edit Form";
    var items = Model.FormItemIList;
}
@*
    public static int TYPE_TEXT_BOX = 0;
    public static int TYPE_TEXT_AREA = 1;
    public static int TYPE_TEXT_RADIO = 2;
    public static int TYPE_TEXT_CHECKBOX = 3;
*@


@using (Html.BeginForm("EditForm", "FormsAdmin", FormMethod.Post, new { @class = "full", @id = "new-form" }))
{
    <div class="form-horizontal">
        <fieldset>
            <legend>Edit Form Content</legend>
            @Html.HiddenFor(m => m.adminGUID)

            <div class="form-group">
                <label class="col-lg-2 control-label">@Html.LabelFor(m => m.Name)</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    <p class="text-warning">@Html.ValidationMessageFor(m => m.Name)</p>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Status, new { @class = "col-lg-2 control-label"})
                <div class="col-lg-10">
                    <div class="checkbox">
                        <label>
                            @Html.CheckBoxFor(m => m.Status)
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label">@Html.LabelFor(m => m.StartDate)</label>
                <div class="col-lg-4">
                    @Html.TextBoxFor(m => m.StartDate, null, new { @Value = DateTime.Now.ToString("MM/dd/yyyy HH:mm"), @class = "date form-control" })
                    @Html.ValidationMessageFor(m => m.StartDate)
                </div>
                <label class="col-lg-1 control-label">@Html.LabelFor(m => m.EndDate)</label>
                <div class="col-lg-4">
                    @Html.TextBoxFor(m => m.EndDate, null, new { @Value = DateTime.Now.AddDays(1).ToString("MM/dd/yyyy HH:mm"), @class = "date form-control" })
                    @Html.ValidationMessageFor(m => m.EndDate)
                </div>
            </div>



            <div class="form-group">
                <label class="col-lg-2 control-label"></label>
                <div class=" col-lg-8">
                    <div id="item-zone">
                        @for (var i = 0; i < items.Count(); ++i)
                        {
                            ViewBag.index = i;
                            ViewBag.TextBoxCount = i;
                            var currentItem = items.ElementAt(i);
                            if (currentItem.type == 2)         {

                                @Html.Partial("~/Views/FormsAdmin/_RadioButtonPartial.cshtml", currentItem)
                            }
                            else if (currentItem.type == 1)
                            {
                                @Html.Partial("~/Views/FormsAdmin/_TextAreaPartial.cshtml", currentItem)
                            }
                            else if (currentItem.type == 0)
                            {
                                @Html.Partial("~/Views/FormsAdmin/_EditTextBoxPartial.cshtml", currentItem)
                            }
                            else if (currentItem.type == 3)
                            {
                                @Html.Partial("~/Views/FormsAdmin/_CheckBoxesPartial.cshtml", currentItem)
                            }
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label">Type</label>
                <div class="col-lg-4">
                    <select class="form-control form-selection-type" id="select">
                        <option value='@Url.Content("~/FormsAdmin/AddTextBox")'>Text Box</option>
                        <option value='@Url.Content("~/FormsAdmin/AddTextArea")'>Text Area</option>
                        <option value='@Url.Content("~/FormsAdmin/AddRadioButton")'>Radio Button</option>
                        <option value='@Url.Content("~/FormsAdmin/AddCheckBoxes")'>Check Box</option>
                    </select>
                </div>
                <label class="col-lg-1 control-label sub-elements" hidden>Number of Options:</label>
                <div class="col-lg-4">
                    <input type="number" class="form-control number-Of-sub-elements sub-elements" value="-1" min="1">
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label ">Count</label>
                <div class="col-lg-10">
                    <input type="number" class="form-control form-selection-count" value="1" min="1">
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="button" class="btn btn-primary btn-lg btn-add-form-item"><span class="glyphicon glyphicon-plus span-space" aria-hidden="true"></span>Add FormItem</button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-8">
                    <button type="submit" class="btn btn-success btn-lg">Submit</button>
                </div>
            </div>

            <div id="test" hidden></div>

            @Html.HiddenFor(m => m.key)

        </fieldset>
    </div>
    
}

    @Scripts.Render("~/Scripts/views/forms-admin-view.js")
    <script type="text/javascript">
        $(document).ready(function () {
            $.extend(form, {
                settings: {
                    UrlAddTextBox: '@Url.Content("~/FormsAdmin/AddTextBox")',
                    UrlAddTextArea: '@Url.Content("~/FormsAdmin/AddTextArea")',
                    UrlAddRadioBtton: '@Url.Content("~/FormsAdmin/AddRadioButton")',
                    UrlAddCheckBoxes: '@Url.Content("~/FormsAdmin/AddCheckBoxes")',
                }
            });
            window.form.init();
        })

    </script>

FormsGeneratorWebApplication/Views/FormsAdmin/EditUserPermission.cshtml
@using FormsGeneratorWebApplication.Models
@model List<ManageUserViewModel>
@{
    ViewBag.Title = "EditUserPermission";
}

<h2>EditUserPermission</h2>

FormsGeneratorWebApplication/Views/FormsAdmin/Email.cshtml
@{
    ViewBag.Title = "Email";

    var guid = ViewBag.GUID;
}

<div class="form-horizontal">
    <fieldset>
        <legend>Email</legend>
        <div class="form-group">
            <label id="email-error-message" class="col-lg-4 text-danger" hidden>Please enter email in correct format</label>
        </div>
    </fieldset>
</div>


<div class="container">
    <div class="row">
        <div class="control-group" id="fields">
            <label class="control-label" for="field1">Enter a Correct Formatted Email for a Recipients.</label>
            <div class="controls">
                <form role="form" autocomplete="off">
                    <div class="entry input-group col-xs-3">
                        <input class="form-control" name="fields[]" type="text" id="email-add-text" placeholder="Type something" />
                        <span class="input-group-btn">
                            <button class="btn btn-success btn-add" type="button">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                        </span>
                    </div>
                </form>
                <br>
                <small>Press <span class="glyphicon glyphicon-plus"></span> to add another form field :)</small>
                @using (Html.BeginForm("Email", "FormsAdmin", FormMethod.Post, new { id = "Email-form", @Class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button id="email-submit-btn" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-send span-space"></span>Send</button>
                            @Html.Hidden("recipients", "", new { Name = "recipients", ID = "email-recp" })
                            @Html.Hidden("guid", "@guid", new { Name = "guid", ID = "email-guid", Value = @guid })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@Scripts.Render("~/Scripts/views/forms-admin-email.js")
<script type="text/javascript">
    $(document).ready(function () {
        $.extend(form, {
            settings: {
   
            }
        });
        window.form.init();
    })

</script>

FormsGeneratorWebApplication/Views/FormsAdmin/EmailSucess.cshtml
@{
    ViewBag.Title = "Email Sucess";
}

<h2>EmailSucess</h2>

FormsGeneratorWebApplication/Views/FormsAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";

}

@*<h2>Welcome To The Admin Page</h2>
    @Html.ActionLink("Make a new Form", "MakeForm", "FormsAdmin")*@
@model FormsGeneratorWebApplication.Models.AdminFormModel

<div id="top-div">
    <div class="form-horizontal">
        <fieldset>
            <legend>Forms Home</legend>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-1">
                    <div class="btn-group">
                        @Html.ActionLink("Create A New Form", "MakeForm", "FormsAdmin", new { @class = "btn btn-info btn-lg" })
                        <div class="btn-group">
                            <a href="#" class="btn btn-success btn-lg"> <span class="glyphicon glyphicon-list-alt span-space"></span> Create form template</a>
                            <a href="#" class="btn btn-success btn-lg dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                            <ul class="dropdown-menu btn-block">
                                <li>@Html.ActionLink("True or False Template", "Template", new { typechoose = 2, numberOfSubElements = 2 }, new { @class = "btn btn-lg" })</li>
                                <li>@Html.ActionLink("TextBox Template", "Template", new { typechoose = 0, numberOfSubElements = 2 }, new { @class = "btn btn-lg" })</li>
                                <li>@Html.ActionLink("TextArea Template", "Template", new { typechoose = 1, numberOfSubElements = 2 }, new { @class = "btn btn-lg" })</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-1">
                    <h3>List of your Forms</h3>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-1">
                    @if (Model.forms.Count > 0)
                    {
                        <table class="table table-striped table-hover ">
                            <thead>
                                <tr class="danger">
                                    <th>Name</th>
                                    <th>Copy</th>
                                    <th>Edit</th>
                                    <th>Statistics</th>
                                    <th>Date Range</th>
                                    <th>Status</th>
                                    <th>Download</th>
                                    <th>Reminder</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (var i = 0; i < Model.forms.Count; ++i)
                                {
                                    <tr class="active">
                                        <td>
                                            <a href="" class="btn btn-link btn-sm text-warning">@Model.forms[i].Name </a>
                                        </td>
                                        <td><input type="button" name="@Model.forms[i].adminGUID" class="btn btn-warning btn-sm" id="Admin-Form-Copy-Button-@i" value="Copy" /></td>
                                        <td><input type="button" name="@Model.forms[i].adminGUID" class="btn btn-warning btn-edit btn-sm" id="Admin-Form-Edit-Button-@i" value="Edit" /></td>
                                        <td><input type="button" name="@Model.forms[i].adminGUID" class="btn btn-warning btn-sm btn-stats" id="Admin-Form-Statistics-Button-@i" value="Statistics" /></td>
                                        <td>
                                            @*@Html.TextBoxFor(m => m.forms[i].StartDate, null, new { @class = "date" })
                                            @Html.TextBoxFor(m => m.forms[i].EndDate, null, new { @class = "date" })*@

                                            <label class="text-warning">@Html.DisplayFor(m => m.forms[i].StartDate) - @Html.DisplayFor(m => m.forms[i].EndDate)</label>
                                        </td>
                                        <td>
                                            @if (Model.forms[i].Status)
                                            {
                                                <label>Enabled</label>
                                            }
                                            else
                                            {  <label>Disabled</label>
                                            }
                                        </td>
                                        <td><input type="button" value="Download" name="@Model.forms[i].adminGUID" class="btn btn-warning btn-sm btn-download" id="Admin-Form-Download-Button-@i" /></td>
                                        <td><input type="button" value="Reminder" name="@Model.forms[i].adminGUID" class="btn btn-warning btn-sm btn-reminder" id="Admin-Form-Reminder-Button-@i" /></td>
                                        <td><label>@Model.completed[i] / @Model.total[i]</label></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div>You have no forms created yet.</div>
                    }
                </div>
            </div>
        </fieldset>
    </div>
</div>
@Scripts.Render("~/Scripts/views/forms-admin-index.js")
<script type="text/javascript">
    $(document).ready(function () {
        $.extend(form, {
            settings: {
                UrlDownload: '@Url.Content("~/FormsAdmin/DownloadAnalytic")',
                UrlEdit: '@Url.Content("~/FormsAdmin/EditForm")',
                UrlStats: '@Url.Content("~/FormsAdmin/Analytic")',
                UrlReminder: '@Url.Content("~/FormsAdmin/reminder")'
            }
        });
        window.form.init();
    })

</script>

FormsGeneratorWebApplication/Views/FormsAdmin/MakeForm.cshtml
@using FormsGeneratorWebApplication.Models;
@{
    ViewBag.Title = "MakeForm";
    ViewBag.TextBoxCount = '0';
}


@model  FormsGeneratorWebApplication.Models.FormsModel


@using (Html.BeginForm("MakeForm", "FormsAdmin", FormMethod.Post, new { @class = "full", @id = "new-form" })) {
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <fieldset>
            <legend>MakeForm</legend>
            @Html.HiddenFor(m => m.Status, new { @Value = true })
            <div class="form-group">
                <label class="col-lg-2 control-label">@Html.LabelFor(m => m.Name)</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control"})
                    <p class="text-warning">@Html.ValidationMessageFor(m => m.Name)</p>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label">@Html.LabelFor(m => m.StartDate)</label>
                <div class="col-lg-4">
                    @Html.TextBoxFor(m => m.StartDate, null, new { @Value = DateTime.Now.ToString("MM/dd/yyyy HH:mm"), @class = "date form-control" })
                    @Html.ValidationMessageFor(m => m.StartDate)
                </div>
                <label class="col-lg-1 control-label">@Html.LabelFor(m => m.EndDate)</label>
                <div class="col-lg-4">
                    @Html.TextBoxFor(m => m.EndDate, null, new { @Value = DateTime.Now.AddDays(1).ToString("MM/dd/yyyy HH:mm"), @class = "date form-control" })
                    @Html.ValidationMessageFor(m => m.EndDate)
                </div>
            </div>

            @*<div class="form-group">
                <label class="col-lg-2 control-label">@Html.LabelFor(m => m.EndDate)</label>
                <div class="col-lg-10">
                    @Html.TextBoxFor(m => m.EndDate, null, new { @Value = DateTime.Now.AddDays(1).ToString("MM/dd/yyyy HH:mm"), @class = "date form-control" })
                    @Html.ValidationMessageFor(m => m.EndDate)
                </div>
            </div>*@

            @*<div class="form-group">
                <label class="col-lg-2 control-label"></label>
                <div class=" col-lg-8">
                    <div id="item-zone">
                       
                    </div>
                </div>
            </div>*@

            <div class="form-group">
                <label class="col-lg-2 control-label"></label>
                <div class=" col-lg-8">
                    <div id="item-zone">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label">Type</label>
                <div class="col-lg-4">
                    <select class="form-control form-selection-type" id="select">
                        <option value='@Url.Content("~/FormsAdmin/AddTextBox")'>Text Box</option>
                        <option value='@Url.Content("~/FormsAdmin/AddTextArea")'>Text Area</option>
                        <option value='@Url.Content("~/FormsAdmin/AddRadioButton")'>Radio Button</option>
                        <option value='@Url.Content("~/FormsAdmin/AddCheckBoxes")'>Check Box</option>
                    </select>
                </div>
                <label class="col-lg-1 control-label sub-elements" hidden>Number of Options:</label>
                <div class="col-lg-4">
                    <input type="number" class="form-control number-Of-sub-elements sub-elements" value="-1" min="1">
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label ">Count</label>
                <div class="col-lg-10">
                    <input type="number" class="form-control form-selection-count" value="1" min="1">
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="button" class="btn btn-primary btn-lg btn-add-form-item"><span class="glyphicon glyphicon-plus span-space" aria-hidden="true"></span>Add FormItem</button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-8">
                    <button type="submit" class="btn btn-success btn-lg">Next</button>
                </div>
            </div>
        </fieldset>
    </div>
    <div id="test" hidden></div>
}

@Scripts.Render("~/Scripts/views/forms-admin-view.js")
<script type="text/javascript">
    $(document).ready(function () {
        $.extend(form, {
            settings: {
                UrlAddTextBox: '@Url.Content("~/FormsAdmin/AddTextBox")',
                UrlAddTextArea: '@Url.Content("~/FormsAdmin/AddTextArea")',
                UrlAddRadioBtton: '@Url.Content("~/FormsAdmin/AddRadioButton")',
                UrlAddCheckBoxes: '@Url.Content("~/FormsAdmin/AddCheckBoxes")',
            }
        });
        window.form.init();
    })

</script>

FormsGeneratorWebApplication/Views/FormsAdmin/Sucess.cshtml
 @{
    ViewBag.Title = "Sucess";

    var lnk = ViewBag.GUID;
   
}

<h2>Sucess</h2>

Form created sucessfully:

<a href="@lnk">View Form</a>

FormsGeneratorWebApplication/Views/FormsAdmin/_TextBoxPartial.cshtml
@model  FormsGeneratorWebApplication.Models.TextBoxModel

@{
    var index = Convert.ToInt16((int)ViewBag.TextBoxCount);
}

<div class="ui-accordion-header">
    <div class="form-item">
        <h3>Text Box</h3>
    </div>
</div>
<div>
    <div class="form-group">
        <div class="form-item">
            @Html.LabelFor(m => m.question)
            @Html.TextBoxFor(m => m.question, new { Name = "[" + index + "].question" })
        </div>

        <div class="form-item">
            @Html.LabelFor(m => m.value)
            @Html.TextBoxFor(m => m.value, new { Name = "[" + index + "].value" })
        </div>
    </div>
        @Html.HiddenFor(m => m.postion, new { Name = "[" + index + "].postion" })
</div>

FormsGeneratorWebApplication/Views/FormsAdmin/t.cshtml
test
<div id="m" style="height:100px;"></div>